services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: openq
      POSTGRES_PASSWORD: OpenQ123!
      POSTGRES_DB: openq
    ports:
      - "5432:5432"
    volumes:
      - openq_db_data:/var/lib/postgresql/data

volumes:
  openq_db_data: